package organizadorasistencia;

public class OrganizadorInterfaz extends javax.swing.JFrame {
    public OrganizadorInterfaz() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        salir = new javax.swing.JButton();
        Ok = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        materiaIngreso = new javax.swing.JLabel();
        diaIngreso = new javax.swing.JLabel();
        horaIngreso = new javax.swing.JLabel();
        bloqueIngreso = new javax.swing.JLabel();
        aulaIngreso = new javax.swing.JLabel();
        aforoIngreso = new javax.swing.JLabel();
        numEstudiantesIngreso = new javax.swing.JLabel();
        estudiantesIngreso = new javax.swing.JLabel();
        numListasIngreso = new javax.swing.JLabel();
        dia = new javax.swing.JTextField();
        materia = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        bloque = new javax.swing.JTextField();
        aula = new javax.swing.JTextField();
        aforo = new javax.swing.JTextField();
        listasnum = new javax.swing.JTextField();
        listaEstudiantes = new javax.swing.JTextField();
        numEstudiantes = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salir.setBackground(new java.awt.Color(255, 255, 255));
        salir.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        bg.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, -1, 30));

        Ok.setBackground(new java.awt.Color(255, 255, 255));
        Ok.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        Ok.setText("OK");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });
        bg.add(Ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 550, -1, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo (2).png"))); // NOI18N
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 290, 170));

        materiaIngreso.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        materiaIngreso.setText("Ingrese la materia:");
        bg.add(materiaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, 40));

        diaIngreso.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        diaIngreso.setText("Ingrese el dia de la clase:");
        bg.add(diaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 20));

        horaIngreso.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        horaIngreso.setText("Ingrese la hora de la clase (Formato 24hrs):");
        bg.add(horaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        bloqueIngreso.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        bloqueIngreso.setText("Ingrese el bloque de la clase:");
        bg.add(bloqueIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        aulaIngreso.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        aulaIngreso.setText("Ingrese el aula de la clase:");
        bg.add(aulaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        aforoIngreso.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        aforoIngreso.setText("Ingrese el aforo del aula: ");
        bg.add(aforoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, 30));

        numEstudiantesIngreso.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        numEstudiantesIngreso.setText("Ingrese el número de estudiantes: ");
        bg.add(numEstudiantesIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 30));

        estudiantesIngreso.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        estudiantesIngreso.setText("Ingrese la lista de estudiantes:");
        bg.add(estudiantesIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 240, 20));

        numListasIngreso.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        numListasIngreso.setText("Ingrese el número de listas que desea crear:");
        bg.add(numListasIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 260, -1));
        bg.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 250, 40));

        materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaActionPerformed(evt);
            }
        });
        bg.add(materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 250, 40));
        bg.add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 250, 40));
        bg.add(bloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 250, 40));
        bg.add(aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 250, 40));
        bg.add(aforo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 250, 40));

        listasnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listasnumActionPerformed(evt);
            }
        });
        bg.add(listasnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 250, 40));

        listaEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaEstudiantesActionPerformed(evt);
            }
        });
        bg.add(listaEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 250, 40));
        bg.add(numEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 250, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eafit biblioteca.jpg"))); // NOI18N
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, -6, 320, 600));

        jPanel1.setBackground(new java.awt.Color(156, 178, 255));

        jLabel2.setBackground(new java.awt.Color(176, 186, 229));
        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel2.setText("Organizador de Asistencia");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Checklist-PNG-Image.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 90));

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("de cada alumno)");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, 20));

        registrar.setBackground(new java.awt.Color(176, 186, 229));
        registrar.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        registrar.setText("REGISTRAR");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        bg.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 120, 30));

        jLabel5.setFont(new java.awt.Font("Helvetica", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("(haga click en registrar cuando escriba el nombre ");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materiaActionPerformed

    private void listasnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listasnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listasnumActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_salirMouseClicked

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        String mat = materia.getText();
        String day = dia.getText();
        String hour = hora.getText();
        String b = bloque.getText();
        int bloque = Integer.valueOf(b);
        String a = aula.getText();
        int aula = Integer.valueOf(a);
        String af = aforo.getText();
        int aforo = Integer.valueOf(af);
        String numEs = numEstudiantes.getText();
        int numEstudiantes = Integer.valueOf(numEs);
        String numLis = listasnum.getText();
        int numListas = Integer.valueOf(numLis);
        String nombreEstudiantes = listaEstudiantes.getText();
        
        
        Procesamiento.asignarAsistencia();
        Page2 p2 = new Page2();
        p2.setVisible(true);
        p2.materia = mat;
        p2.hora = hour;
        p2.dia = day;
        p2.aula= b+"-"+a;
    }//GEN-LAST:event_OkActionPerformed

    private void listaEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaEstudiantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaEstudiantesActionPerformed
    int i = 0;
    
    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        String mat = materia.getText();
        String day = dia.getText();
        String hour = hora.getText();
        String b = bloque.getText();
        int bloque = Integer.valueOf(b);
        String a = aula.getText();
        int aula = Integer.valueOf(a);
        String af = aforo.getText();
        int aforo = Integer.valueOf(af);
        String numEs = numEstudiantes.getText();
        int numEstudiantes = Integer.valueOf(numEs);
        String numLis = listasnum.getText();
        int numListas = Integer.valueOf(numLis);
      
        if(i == 0){
        Captura.ingresoDatos(mat, day, hour, bloque, aula, aforo, numEstudiantes, numListas);
        }
        if(i<numEstudiantes){
            Captura.estudiantes[i] = listaEstudiantes.getText();
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Solo puede ingresar "+(numEstudiantes)+" estudiantes.");
        }
       i++;
       listaEstudiantes.setText("");
        
    }//GEN-LAST:event_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrganizadorInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrganizadorInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrganizadorInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrganizadorInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganizadorInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ok;
    private javax.swing.JTextField aforo;
    private javax.swing.JLabel aforoIngreso;
    private javax.swing.JTextField aula;
    private javax.swing.JLabel aulaIngreso;
    private javax.swing.JPanel bg;
    private javax.swing.JTextField bloque;
    private javax.swing.JLabel bloqueIngreso;
    private javax.swing.JTextField dia;
    private javax.swing.JLabel diaIngreso;
    private javax.swing.JLabel estudiantesIngreso;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel horaIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField listaEstudiantes;
    private javax.swing.JTextField listasnum;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField materia;
    private javax.swing.JLabel materiaIngreso;
    private javax.swing.JTextField numEstudiantes;
    private javax.swing.JLabel numEstudiantesIngreso;
    private javax.swing.JLabel numListasIngreso;
    private javax.swing.JButton registrar;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
